on: push
    
jobs:
    build:
        runs-on: ubuntu-24.04
        strategy:
            fail-fast: false
            matrix:
                color: [0, 1, 2, 3]
        steps:
        - run: |
              echo 2
